excerpt_separator: ""
highlighter: rouge
markdown: kramdown
url: http://mikelevins.github.io
title: engine of joy 
tagline: mikel evins
description: What I'm saying about what I'm thinking
paginate: 3
